name: cftracker_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  desktop_window: ^0.4.0
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_clean_architecture: ^6.0.1
  flutter_screenutil: ^5.9.3
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.10+1
  window_manager: ^0.4.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
